"""Risk recomputation."""
from __future__ import annotations

from fastapi import APIRouter, Depends, Request
from sqlalchemy.orm import Session

from ..db import get_db
from ..deps import Principal, audit, require_authority
from ..models import Zone
from ..schemas import RecomputeRequest, RecomputeResponse
from ..services import risk_service, spatial
from ..ws import EVENT_SUMMARY, manager

router = APIRouter(prefix="/risk", tags=["risk"])


@router.post("/recompute", response_model=RecomputeResponse,
             summary="Recompute risk for every zone (or a subset)")
def recompute(body: RecomputeRequest, request: Request,
              db: Session = Depends(get_db),
              principal: Principal = Depends(require_authority)) -> RecomputeResponse:
    query = db.query(Zone).order_by(Zone.id)
    if body.zone_ids:
        query = query.filter(Zone.id.in_(body.zone_ids))
    zones = query.all()

    results = [
        risk_service.compute_zone_risk(db, z, trigger="manual", raise_alerts=body.raise_alerts)
        for z in zones
    ]
    db.commit()

    audit(db, principal, "recompute", "risk", "",
          request, {"zones": len(results), "raise_alerts": body.raise_alerts})
    manager.publish_threadsafe(EVENT_SUMMARY, spatial.dashboard_summary(db))

    return RecomputeResponse(
        computed=len(results),
        model_version=risk_service.registry.version,
        results=results,
    )


@router.get("/model", summary="Which model is loaded (never returns accuracy figures)")
def model_info() -> dict:
    reg = risk_service.registry
    return {
        "loaded": reg.loaded,
        "model_version": reg.version,
        "trained_at": reg.meta.get("trained_at"),
        "features": reg.meta.get("features", []),
        "calibration": reg.meta.get("calibration"),
        "data_provenance": reg.meta.get(
            "data_provenance",
            "SIMULATED — generated by scripts/seed.py, not an official dataset",
        ),
        "load_error": reg.load_error,
        "note": ("Performance metrics are deliberately not served. Accuracy figures "
                 "measured on synthetic data would misrepresent real-world skill."),
        "demo_data": True,
    }
