"""initial schema — PostGIS extension and every BHOOSHAKTI AI table

Revision ID: 0001_initial
Revises:

Explicit DDL, deliberately frozen at the pre-Open-Meteo schema. An earlier
version of this file called Base.metadata.create_all(), which meant the
"baseline" silently tracked whatever the models looked like today — so 0002
then tried to add columns the baseline had already created. A baseline has to
be a fixed point in history, not a mirror of HEAD.
"""
from __future__ import annotations

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('span_m', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'BLOCKED', name='bridge_status_enum'), nullable=False),
    sa.Column('road_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('road_class', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESTRICTED', 'BLOCKED', name='road_status_enum'), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('status_note', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('authority', 'field_officer', 'citizen', name='role_enum'), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('is_cut_off', sa.Boolean(), nullable=False),
    sa.Column('cut_off_reason', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('slope_deg', sa.Float(), nullable=False),
    sa.Column('aspect_deg', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.Column('lithology', sa.String(length=64), nullable=False),
    sa.Column('land_cover', sa.String(length=64), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('citizen_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('geo_valid', sa.Boolean(), nullable=False),
    sa.Column('geo_note', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ESCALATED', name='report_status_enum'), nullable=False),
    sa.Column('moderated_by', sa.String(length=64), nullable=False),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_reports_created_at'), 'citizen_reports', ['created_at'], unique=False)
    op.create_table('field_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('officer_name', sa.String(length=128), nullable=False),
    sa.Column('verdict', sa.Enum('CONFIRMED', 'DENIED', 'UNCERTAIN', name='verdict_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_offline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_reports_client_uuid'), 'field_reports', ['client_uuid'], unique=True)
    op.create_table('historical_landslides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_24h', sa.Float(), nullable=False),
    sa.Column('rainfall_72h', sa.Float(), nullable=False),
    sa.Column('antecedent_rain_15d', sa.Float(), nullable=False),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=False),
    sa.Column('slope_deg', sa.Float(), nullable=False),
    sa.Column('aspect_deg', sa.Float(), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.Column('lithology', sa.String(length=64), nullable=False),
    sa.Column('land_cover', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('fatalities', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_landslides_occurred_at'), 'historical_landslides', ['occurred_at'], unique=False)
    op.create_table('rainfall_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'ts', name='uq_rainfall_zone_hour')
    )
    op.create_index('ix_rainfall_zone_ts', 'rainfall_readings', ['zone_id', 'ts'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FAILED', 'MAINTENANCE', name='sensor_status_enum'), nullable=False),
    sa.Column('sensor_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_nodes_node_id'), 'sensor_nodes', ['node_id'], unique=True)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('tilt_deg', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('ingested_via', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_reading_node_ts', 'sensor_readings', ['node_id', 'ts'], unique=False)
    op.create_index(op.f('ix_sensor_readings_node_id'), 'sensor_readings', ['node_id'], unique=False)
    op.create_table('soil_moisture_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moisture_pct', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'ts', name='uq_soil_zone_hour')
    )
    op.create_index('ix_soil_zone_ts', 'soil_moisture_readings', ['zone_id', 'ts'], unique=False)
    op.create_table('zone_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'zone_id', name='uq_assignment')
    )
    op.create_table('zone_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MODERATE', 'HIGH', 'CRITICAL', name='severity_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('rainfall_24h', sa.Float(), nullable=False),
    sa.Column('rainfall_72h', sa.Float(), nullable=False),
    sa.Column('antecedent_rain_15d', sa.Float(), nullable=False),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=False),
    sa.Column('forecast_24h_mm', sa.Float(), nullable=False),
    sa.Column('sensor_health', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zone_risk_zone_time', 'zone_risk', ['zone_id', 'computed_at'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SIMULATED', name='delivery_status_enum'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_deliveries')
    op.drop_index('ix_zone_risk_zone_time', table_name='zone_risk')
    op.drop_table('zone_risk')
    op.drop_table('zone_assignments')
    op.drop_index('ix_soil_zone_ts', table_name='soil_moisture_readings')
    op.drop_table('soil_moisture_readings')
    op.drop_index(op.f('ix_sensor_readings_node_id'), table_name='sensor_readings')
    op.drop_index('ix_sensor_reading_node_ts', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensor_nodes_node_id'), table_name='sensor_nodes')
    op.drop_table('sensor_nodes')
    op.drop_table('response_actions')
    op.drop_index('ix_rainfall_zone_ts', table_name='rainfall_readings')
    op.drop_table('rainfall_readings')
    op.drop_index(op.f('ix_historical_landslides_occurred_at'), table_name='historical_landslides')
    op.drop_table('historical_landslides')
    op.drop_index(op.f('ix_field_reports_client_uuid'), table_name='field_reports')
    op.drop_table('field_reports')
    op.drop_index(op.f('ix_citizen_reports_created_at'), table_name='citizen_reports')
    op.drop_table('citizen_reports')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('road_segments')
    op.drop_table('bridges')
    # ### end Alembic commands ###
    # Enum types outlive their tables in PostgreSQL; without this a re-upgrade
    # fails on "type already exists".
    for enum_name in (
        "role_enum", "severity_enum", "alert_severity_enum", "sensor_status_enum",
        "road_status_enum", "bridge_status_enum", "report_status_enum",
        "verdict_enum", "delivery_status_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
